name: Minetrax
version: '${version}'
main: com.xinecraft.minetrax.bukkit.MinetraxBukkit
api-version: '1.13'
authors: [ Xinecraft ]
description: Minetrax Plugin
depend: [ Vault ]
softdepend: [
  # Chat plugins
  Herochat, Legendchat, LunaChat, TownyChat, UltimateChat, VentureChat, EpicCore,
  # Vanish plugins
  Essentials, PhantomAdmin, SuperVanish, VanishNoPacket, PremiumVanish,
  # Permissions plugins
  LuckPerms,
  # Misc. plugins
  ViaVersion, SkinsRestorer, Multiverse-Core, PlaceholderAPI, mcMMO, dynmap, Skript,
  # Ban plugins
  LiteBans, LibertyBans, AdvancedBan
]
commands:
  account-link:
    permission: minetrax.link.use
    description: Link player to an account in web
    aliases:
      - link-account
      - link
      - accountlink
      - websitelink
      - verify
  ww:
    permission: minetrax.ww.use
    aliases:
      - webwhois
      - mwhois
    description: Run a web whois against a player username.
  minetrax:
    permission: minetrax.admin
    description: Minetrax admin commands
    aliases:
      - mtx

permissions:
    minetrax.ww.use:
        description: Allows player to run /ww command
        default: op
    minetrax.link.use:
        description: Allows player to run /account-link command
        default: true
    minetrax.admin:
        description: Player with this permission will be consider admin and can run minetrax admin commands
        default: op
