name: Minetrax
version: '${version}'
main: com.xinecraft.minetrax.Minetrax
api-version: 1.13
authors: [ Xinecraft ]
description: Minetrax Plugin
depend: [ Vault ]
softdepend: [
  # Chat plugins
  Herochat, Legendchat, LunaChat, TownyChat, UltimateChat, VentureChat, EpicCore,
  # Vanish plugins
  Essentials, PhantomAdmin, SuperVanish, VanishNoPacket, PremiumVanish,
  # Permissions plugins
  LuckPerms,
  # Misc. plugins
  ViaVersion, SkinsRestorer, Multiverse-Core, PlaceholderAPI, mcMMO, dynmap, Skript
]
commands:
  account-link:
    description: Link player to an account in web
    aliases:
      - link-account
      - link
      - accountlink
      - websitelink
      - verify
  ww:
    aliases:
      - webwhois
      - mwhois
    description: Run a web whois against a player username.
  websay:
    description: This is just dumb
